export default {
  getNews: "news/get",
  getDJYDT: 'DJYDT/get',
  getDYLSF: 'DYLSF/get',
  getZZXX: 'ZZXX/get',
  getSSSDX: 'SSSDX/get',
  getSSSDP: 'SSSDP/get',
  getZDJS: 'ZDJS/get',
  getTSHD: 'TSHD/get',
  getTZZZD: 'TZZZD/get',
  getLBT: 'LBT/get',
  getDSSDJT: 'getData',
  userLogin:'login/login',
  getUsers:'users/getOne',
  logOut:'logout/logout',
  xinXi:'users/update',
  xinmiMa:'XGMM/update',
  huiBao:'SXHB/add',
  getbranch:'branch/get',
  getMZPY:'MZPY/getMZPY',
  canPING:'users/getBranchUser',
  grZj:'GRZJ/add',
  hqZj:'GRZJ/getOther',
  panDuan:'isLogin/isLogin',
  yunTianjia:'invitation/add',
  yunHuoqu:'invitation/get',
  yunPinglun:'invitation/reply',
  yunHuoping:'invitation/getReply',
}
